export {
  listContract,
  tableContract,
  tableBodyContract,
  tableRowContract,
  colgroupContract,
  dlContract,
  selectContract,
  optgroupContract,
  pictureContract,
  figureContract,
  detailsContract,
  fieldsetContract,
  htmlContracts,
} from './contracts'
