import type { AriaAttribute, AriaAttributeRoleMap, AriaRoleName } from './types'

// WAI-ARIA 1.2 — states and properties scoped to specific roles ("attribute → the concrete roles
// that support it", globals and prohibited attributes removed).
//
// This table is kept in lockstep with `aria-support.generated.json` (derived from `aria-query`
// via `scripts/generate-aria-support.ts`); `role-restricted-attributes.spec-conformance.test.ts`
// fails on any drift. Edit it only alongside a fixture regeneration and a documented reason —
// `aria-dropeffect` / `aria-grabbed` are the one intentional omission (deprecated since ARIA 1.1).
//
// An `aria-*` attribute absent from this map (and not global) is accepted unconditionally: an
// unknown attribute may be valid per a future spec revision or a custom role. So the table
// under-reports rather than false-positives on the attributes it does not model.
export const ROLE_RESTRICTED_ATTRIBUTES: AriaAttributeRoleMap = new Map<
  AriaAttribute,
  ReadonlySet<AriaRoleName>
>([
  [
    'aria-activedescendant',
    new Set([
      'application',
      'combobox',
      'grid',
      'group',
      'listbox',
      'menu',
      'menubar',
      'radiogroup',
      'row',
      'searchbox',
      'spinbutton',
      'tablist',
      'textbox',
      'toolbar',
      'tree',
      'treegrid',
    ]),
  ],
  ['aria-autocomplete', new Set(['combobox', 'searchbox', 'textbox'])],
  [
    'aria-checked',
    new Set([
      'checkbox',
      'menuitemcheckbox',
      'menuitemradio',
      'option',
      'radio',
      'switch',
      'treeitem',
    ]),
  ],
  ['aria-colcount', new Set(['grid', 'table', 'treegrid'])],
  ['aria-colindex', new Set(['cell', 'columnheader', 'gridcell', 'row', 'rowheader'])],
  ['aria-colspan', new Set(['cell', 'columnheader', 'gridcell', 'rowheader'])],
  [
    'aria-expanded',
    new Set([
      'application',
      'button',
      'checkbox',
      'columnheader',
      'combobox',
      'gridcell',
      'link',
      'listbox',
      'menuitem',
      'menuitemcheckbox',
      'menuitemradio',
      'row',
      'rowheader',
      'switch',
      'tab',
      'treeitem',
    ]),
  ],
  [
    'aria-haspopup',
    new Set([
      'application',
      'button',
      'columnheader',
      'combobox',
      'gridcell',
      'link',
      'menuitem',
      'menuitemcheckbox',
      'menuitemradio',
      'rowheader',
      'searchbox',
      'slider',
      'tab',
      'textbox',
      'treeitem',
    ]),
  ],
  [
    'aria-invalid',
    new Set([
      'application',
      'checkbox',
      'columnheader',
      'combobox',
      'gridcell',
      'listbox',
      'menuitemcheckbox',
      'menuitemradio',
      'radiogroup',
      'rowheader',
      'searchbox',
      'slider',
      'spinbutton',
      'switch',
      'textbox',
      'tree',
      'treegrid',
    ]),
  ],
  ['aria-level', new Set(['heading', 'listitem', 'row', 'tablist', 'treeitem'])],
  ['aria-modal', new Set(['alertdialog', 'dialog'])],
  ['aria-multiline', new Set(['searchbox', 'textbox'])],
  ['aria-multiselectable', new Set(['grid', 'listbox', 'tablist', 'tree', 'treegrid'])],
  [
    'aria-orientation',
    new Set([
      'listbox',
      'menu',
      'menubar',
      'radiogroup',
      'scrollbar',
      'separator',
      'slider',
      'tablist',
      'toolbar',
      'tree',
      'treegrid',
    ]),
  ],
  ['aria-placeholder', new Set(['searchbox', 'textbox'])],
  [
    'aria-posinset',
    new Set([
      'article',
      'listitem',
      'menuitem',
      'menuitemcheckbox',
      'menuitemradio',
      'option',
      'radio',
      'row',
      'tab',
      'treeitem',
    ]),
  ],
  ['aria-pressed', new Set(['button'])],
  [
    'aria-readonly',
    new Set([
      'checkbox',
      'columnheader',
      'combobox',
      'grid',
      'gridcell',
      'listbox',
      'menuitemcheckbox',
      'menuitemradio',
      'radiogroup',
      'rowheader',
      'searchbox',
      'slider',
      'spinbutton',
      'switch',
      'textbox',
      'treegrid',
    ]),
  ],
  [
    'aria-required',
    new Set([
      'checkbox',
      'columnheader',
      'combobox',
      'gridcell',
      'listbox',
      'menuitemcheckbox',
      'menuitemradio',
      'radiogroup',
      'rowheader',
      'searchbox',
      'spinbutton',
      'switch',
      'textbox',
      'tree',
      'treegrid',
    ]),
  ],
  ['aria-rowcount', new Set(['grid', 'table', 'treegrid'])],
  ['aria-rowindex', new Set(['cell', 'columnheader', 'gridcell', 'row', 'rowheader'])],
  ['aria-rowspan', new Set(['cell', 'columnheader', 'gridcell', 'rowheader'])],
  [
    'aria-selected',
    new Set(['columnheader', 'gridcell', 'option', 'row', 'rowheader', 'tab', 'treeitem']),
  ],
  [
    'aria-setsize',
    new Set([
      'article',
      'listitem',
      'menuitem',
      'menuitemcheckbox',
      'menuitemradio',
      'option',
      'radio',
      'row',
      'tab',
      'treeitem',
    ]),
  ],
  ['aria-sort', new Set(['columnheader', 'rowheader'])],
  [
    'aria-valuemax',
    new Set(['meter', 'progressbar', 'scrollbar', 'separator', 'slider', 'spinbutton']),
  ],
  [
    'aria-valuemin',
    new Set(['meter', 'progressbar', 'scrollbar', 'separator', 'slider', 'spinbutton']),
  ],
  [
    'aria-valuenow',
    new Set(['meter', 'progressbar', 'scrollbar', 'separator', 'slider', 'spinbutton']),
  ],
  [
    'aria-valuetext',
    new Set(['meter', 'progressbar', 'scrollbar', 'separator', 'slider', 'spinbutton']),
  ],
])
