version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    groups:
      internal:
        patterns:
          - "@praxis-ui/*"

      build:
        patterns:
          - "vite*"
          - "rollup*"
          - "tsup"
          - "typescript"

      react:
        patterns:
          - "react*"
          - "@types/react*"
