export type {
  AriaContext,
  AriaFix,
  AriaFixResult,
  AriaInvalidResult as InvalidResult,
  AriaInvalidWithFix as InvalidWithFix,
  AriaInvalidWithoutFix as InvalidWithoutFix,
  AriaPhase,
  AriaResult,
  AriaRule,
  FixKind,
  RemoveAttributeFixKind,
  Severity,
  ValidResult,
} from '@praxis-kit/primitive/types'
