export type { AriaRole, KnownAriaRole } from '@praxis-kit/contract'
export type {
  AnyRecord,
  ClassName,
  DefaultProps,
  DefaultVariants,
  ElementForTag,
  ElementType,
  EmptyRecord,
  IntrinsicProps,
  IntrinsicTag,
  MergeRecords,
  NonEmptyArray,
  NoPluginProps,
  NoPreset,
  NoVariants,
  PolymorphicRuntime,
  PropsWithRole,
  RecipeMap,
  ResolvedFactoryOptions,
  ResolveTagFn,
  VariantMap,
  VariantProps,
  VariantSelection,
  VariantValue,
} from '@praxis-kit/primitive'
export type * from './aria'
export type * from './class'
export type * from './contract'
export type {
  AllowedOf,
  AnyFactoryOptions,
  ClassPluginResolution,
  DefaultOf,
  EnforcementOptions,
  FactoryOptions,
  NormalizeFn,
  PolymorphicGenerics,
  PropNormalizer,
  PropsOf,
  RecipeOf,
  RenderPipeline,
  ResolvedFactoryShape,
  ResolveInput,
  ResolveOutput,
  ResolverOptions,
  StylingOptions,
  VariantsOf,
} from './factory'
