import type { ClassName, EmptyRecord, StringMap, TagMap } from '../primitives'
import type { AnyClassPluginFactory } from '../class'
import type { CompoundVariant } from '../variants/compound'
import type { DefaultVariants, RecipeMap, VariantMap } from '../variants'

export type StylingOptions<
  V extends Readonly<VariantMap> = Readonly<EmptyRecord>,
  TPreset extends RecipeMap<V> = Readonly<EmptyRecord>,
  TPlugin extends AnyClassPluginFactory = AnyClassPluginFactory,
> = {
  /** Class applied to every instance regardless of variant selection. */
  readonly base?: ClassName
  /**
   * Named variant groups (e.g. `intent`, `size`), each mapping its possible values to a
   * class string. A consumer selects a value per group as a prop (`<Button intent="primary">`).
   */
  readonly variants?: V
  /** Value used for a variant group when the consumer doesn't pass one explicitly. */
  readonly defaults?: Partial<DefaultVariants<V>>
  /**
   * Applies an extra class only when a specific *combination* of variant selections matches —
   * for cases `variants` alone can't express (e.g. `intent: 'primary'` + `size: 'lg'` together
   * need a class neither variant would add on its own).
   */
  readonly compounds?: readonly CompoundVariant<V>[]
  /**
   * Named bundles of variant values, selectable as a single unit via the `recipe` prop (e.g.
   * `<Button recipe="cta">` instead of setting `intent`/`size` individually).
   */
  readonly presets?: TPreset
  /** Maps a resolved tag directly to a raw class string, independent of the variant system. */
  readonly tags?: Readonly<TagMap>
  /**
   * A `ClassPluginFactory` (e.g. the Tailwind layout pipeline) that extends class resolution
   * with its own owned props, layered on top of `variants`/`presets`/`tags`.
   */
  readonly plugin?: TPlugin
  /**
   * A cache-key → resolved-class-string lookup for every statically-known variant
   * combination, skipping runtime class computation entirely when a match is found. Normally
   * generated by a build-time class-extraction plugin rather than hand-authored.
   */
  readonly precomputedClasses?: Readonly<StringMap<string>>
}
