export * from './create-polymorphic-component'
export * from './slot'
export { Slottable } from '@/shared'
export type { SlottableProps } from '@/shared'
export type { PolymorphicProps, PolymorphicComponent, ElementRef } from '@/shared'
export type { ReactFactoryOptions } from '@/shared'
export { mergeRefs } from '@/shared'
