export type AnyRecord = Record<string, unknown>
export type ClassName = string
export type EmptyRecord = Record<never, never>
export type IntrinsicTag = keyof HTMLElementTagNameMap
export type ElementType = IntrinsicTag | (string & {})
export type DefaultProps<T> = T extends AnyRecord ? Partial<T> : never
export type TagMap = Partial<Record<IntrinsicTag | (string & {}), ClassName>>
export type NonEmptyArray<T> = [T, ...T[]]
export type IntrinsicProps = AnyRecord & { role?: string }
export type PropsWithRole = Readonly<IntrinsicProps & { role: string }>
