export { SLOT_NAME } from './constants'
export { invariant, invariantDefined } from './invariant'
export { mergeProps } from './mergeProps'
export { PROP_MERGE_POLICIES, chainHandlers, mergeClassNames, mergeStyles } from './policies'
export type { PropMergePolicy, MergePolicyHandler } from './policies'
export { isReactEventKey, isFunction, isPlainObject } from './predicates'
export type { EventHandler, SlotProps, SlotValidationResult, SlotChildPolicy } from './types'
