export { createPolymorphicComponent } from './create-polymorphic-component'
export type { VueFactoryOptions } from './vue-options'
export { Slottable } from './slot'
export type { SlottableProps } from './slot'
export type { PolymorphicProps, PolymorphicWithAsChild, PolymorphicComponent } from './types'
